---
name: Matthew
surname: McAnear
position: "Senior Data Scientist"
address: "Ann Arbor, MI"
phone: +1 423-277-0411
email: "mcanearm@gmail.com"
linkedin: mcanearm
date: "`r format(Sys.time(), '%Y')`"
docname: "Resume"
headcolor: 333333
header-includes: |
  \pagestyle{empty}
  \AtBeginDocument{\pagenumbering{gobble}}
output: 
  vitae::hyndman
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```


# Professional Experience

```{r work}
all_exp <- list(
  list(
    "company" = "Seer Interactive",
    "title" = "Data Scientist",
    "location" = "Philadelphia, PA",
    "year" = "2014 - 2015",
    "detail" = c(
      "Conducted a web-based experiment on domain recognition using multivariate hierarchical regression, showing that shorter domain names were 10 times more likely to be remembered than longer ones.",
      "Provided support to analytics account managers through programmatic report creation. This initiative cut over 80 hours off monthly reporting tasks."
    )
  ),
  list(
    "company" = "Clear Capital",
    "title" = "Data Scientist I",
    "location" = "Reno, NV",
    "year" = "2015 - 2017",
    "detail" = c(
      "Led a five person development team as the principal developer for Clear Capital’s AVM, a system that generates 150 million weekly predictions and annual revenues exceeding \\$5 million.",
      "Designed and implemented robust webservices using Python, Flask, and AWS Lambda to deliver AVM model predictions and internal company data in real-time through a seamless RESTful interface."
    )
  ),
  list(
    "company" = "Clear Capital",
    "title" = "Data Scientist II",
    "location" = "Reno, NV",
    "year" = "2017 - 2019",
    "detail" = c(
      "Led a team of five to optimize the automated valuation model (AVM), resulting in a reduction of build time and costs by over 90\\%.",
      "Transformed AVM performance from last place among 31 vendors to become the industry leader within just 6 months, contributing to additional annual revenues exceeding \\$1 million.",
      "Devised an event-driven S3 and DynamoDB application to manage 35+ terabytes of MLS photos and metadata with latencies consistently below 500ms.",
      "Applied temporal normalization techniques to enhance model performance and stability, ensuring more reliable and accurate predictions.",
      "Customized the random-forest algorithm prediction process, yielding a 50\\% reduction in prediction outliers and enhanced model precision."
    )
  ),
  list(
    "company" = "Clear Capital",
    "title" = "Senior Machine Learning Engineer",
    "location" = "Reno, NV (Remote)",
    "year" = "2020 - 2021",
    "detail" = c(
      "Launched and managed Redshift data warehouse, supporting ML models, ETL workflows, BI dashboards, and ad-hoc analytical queries.",
      "Developed efficient Hadoop and Pyspark ETL pipelines for data engineering, model fitting, and batch prediction, resulting in an 80\\% reduction in build time.",
      "Authored a quantile-regression based interval recalibration procedure, improving prediction interval coverage from 90\\% to the target of 68\\%.",
      "Architected an A/B model testing framework, boosting experiment throughput by 10-fold.",
      "Replaced a heuristic home complexity scoring engine with a Bayesian model, achieving approximately 40\\% better performance and 99\\% lower costs."
    )
  ),
  list(
    "company" = "Point Predictive",
    "title" = "Senior Data Scientist",
    "location" = "San Diego, CA (Remote)",
    "year" = "2021 - 2023",
    "detail" = c(
      "Developed statistical models to predict early default/chargeoff for auto lenders.",
      "Constructed modular ETL pipelines to securely load sensitive lender data (PPI) into NoSQL and RDBMS databases, significantly reducing load times from over 8 hours to under 30 minutes.",
      "Created high-performance Postgres stored procedures for real-time calculation of historical borrower data, delivering critical aggregate statistics with sub-200ms query times.",
      "Designed a PostgresSQL-based fuzzy matching probabilistic record linkage algorithm to retrieve prior credit applications of incoming borrowers, resulting in 50\\% faster query times and improved match rates.",
      "Automated Snowflake queries for model distribution drift detection, streamlining weekly efforts from 5 hours to just 10 minutes."
    )
  )
)

tribble(
  ~company, ~location, ~title, ~year, ~detail,
  all_exp[[5]]$title, all_exp[[5]]$company, all_exp[[5]]$location, all_exp[[5]]$year, all_exp[[5]]$detail, 
  all_exp[[4]]$title, all_exp[[4]]$company, all_exp[[4]]$location, all_exp[[4]]$year, all_exp[[4]]$detail, 
  all_exp[[3]]$title, all_exp[[3]]$company, all_exp[[3]]$location, all_exp[[3]]$year, all_exp[[3]]$detail, 
  all_exp[[2]]$title, all_exp[[2]]$company, all_exp[[2]]$location, all_exp[[2]]$year, all_exp[[2]]$detail, 
  all_exp[[1]]$title, all_exp[[1]]$company, all_exp[[1]]$location, all_exp[[1]]$year, all_exp[[1]]$detail, 
) %>%
  detailed_entries(with = title, what = company, when = year, where = location, why = detail, .protect = FALSE)
```

# Research Experience

```{r research, results='markup'}

all_exp <- list(
  list(
    "institution" = "Bucknell Environmental Center",
    "title" = "Research Assistant",
    "location" = "Bucknell University",
    "year" = "2012-2013",
    "detail" = c(
      "Investigated effects of social capital on health status using ACTION Health survey of 3300 respondents in the Central Susquehanna Region"
    )
  ),
  list(
    "institution" = "School of Policy and Practice",
    "title" = "Research Assistant",
    "location" = "University of Pennsylvania",
    "year" = "2014",
    "detail" = c(
      	"Support research on competition between charter and independent schools in Texas by gathering, cleaning, and analyzing raw data",
        "Carried out analysis of children's survey responses for Comegys Elementary School on behalf of the Philadelphia Eagles"
    )
  ),
  list(
    "institution" = "Statistics Department",
    "title" = "Research Assistant",
    "location" = "University of Michigan",
    "year" = "2023",
    "detail" = c(
      	"Fit Gaussian process time-series models for prediction of solar weather events on Slurm cluster"
    )
  )
)


tribble(
  ~institution, ~title, ~location, ~year, ~detail,
  all_exp[[3]]$title, all_exp[[3]]$institution, all_exp[[3]]$location, all_exp[[3]]$year, all_exp[[3]]$detail, 
  all_exp[[2]]$title, all_exp[[2]]$institution, all_exp[[2]]$location, all_exp[[2]]$year, all_exp[[2]]$detail, # skip this one for space
  all_exp[[1]]$title, all_exp[[1]]$institution, all_exp[[1]]$location, all_exp[[1]]$year, all_exp[[1]]$detail, 
) %>%
  detailed_entries(with = title, what = institution, when = year, where = location, why = detail, .protect = FALSE)

```


# Skills

```{r techskills, results='markup', include=TRUE}
tribble(
   ~Technologies, ~detail,
   "Expertise", "Data Science, Machine Learning, Model Validation, Data Engineering, Databases, Dashboarding, A/B Testing, Time-Series Analysis, Visualization",
   "Technologies", "R, Python, Linux, SQL, AWS, Snowflake, Docker, PostgreSQL, Looker, Slurm, Hadoop, Spark, REST, Flask, Git",
   "Packages", "scikit-learn, PyMC, numpyro, jax, pandas, numpy, pyspark, PyTorch, sqlalchemy",
   "Algorithms", "RandomForest, Regression, Clustering, XGBoost, MCMC sampling, Variational Inference, Bayesian Deep Learning, Hierarchical Modeling, Record Linkage, KNN, Clustering, MapReduce"
)  %>%
  detailed_entries(what=Technologies, why=detail)
```


# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Where, ~ Institution, ~ Detail,
  "M.S., Applied Statistics", "Present", "University of Michigan", "Ann Arbor, MI", c(),
  "M.S., Nonprofit/NGO Leadership", "2014", "University of Pennsylvania", "Philadelphia, PA", c("Donald J. Deutsch Endowed Graduate Fellowship"),
  "B.A., Mathematics \\& Economics", "2013", "Bucknell University", "Lewisburg, PA", c("\\textit{Magna cum laude}", "National Merit Finalist Scholarship", "Dean's Scholarship", "Omicron Delta Epsilon Economics Honor Society"),
) %>%
  detailed_entries(what = Degree, when = Year, with = Institution, where = Where, why = Detail, .protect = FALSE)
```



